on:
  push:
    branches:
    - main
    - release/*
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
        output_file: "diagram.svg"
        should_push: false
    - uses: actions/upload-artifact@v4.6.2
      with:
    # A file, directory or wildcard pattern that describes what to upload
        path: "diagram.svg"
    # The desired behavior if no files are found using the provided path.

 
        
      
    
  
  
